FROM maven:3.9.9-eclipse-temurin-17
RUN apt-get update \
    && apt-get install -y --no-install-recommends wget gnupg ca-certificates fonts-liberation unzip xz-utils \
        libdbus-glib-1-2 libxt6t64 libasound2t64 libgtk-3-0t64 \
    && wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y /tmp/google-chrome.deb \
    && rm -f /tmp/google-chrome.deb \
    && wget -q -O /tmp/firefox.tar.xz "https://download.mozilla.org/?product=firefox-esr-latest&os=linux64&lang=en-US" \
    && tar -xJf /tmp/firefox.tar.xz -C /opt \
    && rm -f /tmp/firefox.tar.xz \
    && ln -sf /opt/firefox/firefox /usr/local/bin/firefox \
    && rm -rf /var/lib/apt/lists/*
ENV CHROME_BIN=/usr/bin/google-chrome
ENV FIREFOX_BIN=/opt/firefox/firefox
ARG ALLURE_VERSION=2.29.0
RUN wget -q -O /tmp/allure.zip "https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip" \
    && unzip -q /tmp/allure.zip -d /opt \
    && mv /opt/allure-${ALLURE_VERSION} /opt/allure \
    && rm -f /tmp/allure.zip
ENV PATH="/opt/allure/bin:${PATH}"
